# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Test
on: 
  push:
    branches:
      - main
      - sub
  pull_request:
    branches:
      - main
      - sub
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
    # - name: Build
    #   run: xcodebuild -workspace Chit-Chat.xcworkspace -scheme Chit-Chat -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Test
      run: xcodebuild -workspace Chit-Chat.xcworkspace -scheme Chit-Chat -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test