# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ci

on: 
  push:
    branches:
      - main
      - sub
  pull_request:
    branches:
      - main
      - sub

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    - name: Build and test
      run: xcodebuild clean build test -workspace Chit-Chat.xcworkspace -scheme Chit-Chat -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
